# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c09d94276bb25ee4e4c22774a134ed006c2e33a833182a89b1fd7da901a3ccdf9af8a28661a8daffeb11c88d931ca8a3f19fe62e1f19ab6edea8c18dd9c069b

test:
  secret_key_base: 3e30f61ec81de64594daf1c0a19b62c6d7ef53f58b442d1c58e5d1abfed066f7417bf4f0ba15aa8ddff4a3937f1e51e50125d995908ad9d948da8586b5b31d32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
